version: "3.9"

services:

  database:
    #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: maindb
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=main-db
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: app
    restart: on-failure
    ports:
      - 3333:3333
    environment:
      - DATABASE_URL=postgresql://docker:docker@main-db:5432/database?schema=public
      - PORT=3333
    volumes:
      - ./:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
